name: Default Pipeline

on:
  push:
    branches:
      - primary
    tags:
      - '*'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        repository: blazephoenix/extra-life
        tag_with_ref: true
    - name: Remote SSH Commands
      uses: fifsky/ssh-action@v.0.0.4
      with:
        command: |
          docker pull blazephoenix/extra-life:primary
          docker stop ${{ secrets.APP_NAME }}
          docker rm ${{ secrets.APP_NAME }}
          docker run --detach --name ${{ secrets.APP_NAME }} --publish 80:8080 blazephoenix/extra-life:primary
        host: ${{ secrets.HOST }}
        user: ec2-user
        key: ${{ secrets.PRIVATE_KEY }}
