name: Live Channel Deploy

on:
  push:
    branches:
      - primary
    tags:
      - '*'

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build/Push Container to GCR
        uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: gcr.io
          project_id: extra-life-slalom
          image_name: el-web-app
          image_tag: live
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: el-web-app-live
          image: gcr.io/extra-life-slalom/el-web-app:live
          credentials: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: Deploy to Live Channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EXTRA_LIFE_SLALOM }}
          projectId: extra-life-slalom
          channelId: live
